2021-06-10 08:57:52,836 [main] INFO  o.a.a.d.o.w.e.s.c.Controller Starting Controller using Java 11.0.9 on Isurus-MacBook-Pro.local with PID 6403 (/Users/isururanawaka/Documents/Airavata_Repository/airavata-data-lake/data-orchestrator/workflow-engine/workflow-engine-core/target/classes started by isururanawaka in /Users/isururanawaka/Documents/Airavata_Repository/airavata-data-lake/data-orchestrator/workflow-engine/workflow-engine-core) []
2021-06-10 08:57:52,841 [main] INFO  o.a.a.d.o.w.e.s.c.Controller No active profile set, falling back to default profiles: default []
2021-06-10 08:57:53,420 [main] INFO  o.a.a.d.o.w.e.s.c.Controller Started Controller in 0.881 seconds (JVM running for 1.206) []
2021-06-10 08:57:53,421 [main] INFO  o.a.a.d.o.w.e.s.c.Controller Starting Cluster Controller ...... []
2021-06-10 08:57:53,758 [main] INFO  o.a.a.d.o.w.e.s.c.Controller Connection to helix cluster : datalake with name : datalake_controller []
2021-06-10 08:57:53,759 [main] INFO  o.a.a.d.o.w.e.s.c.Controller Zookeeper connection string localhost:2181 []
2021-06-10 09:43:44,845 [main] INFO  o.a.a.d.o.w.e.s.c.Controller Starting Controller v0.01-SNAPSHOT using Java 11.0.9 on Isurus-MacBook-Pro.local with PID 6877 (/Users/isururanawaka/Documents/Airavata_Repository/airavata-data-lake/data-orchestrator/workflow-engine/workflow-engine-core/target/workflow-engine-core-0.01-SNAPSHOT.jar started by isururanawaka in /Users/isururanawaka/Documents/Airavata_Repository/airavata-data-lake/data-orchestrator/workflow-engine/workflow-engine-core) []
2021-06-10 09:43:44,849 [main] INFO  o.a.a.d.o.w.e.s.c.Controller No active profile set, falling back to default profiles: default []
2021-06-10 09:43:45,777 [main] INFO  o.a.a.d.o.w.e.s.c.Controller Started Controller in 1.555 seconds (JVM running for 2.114) []
2021-06-10 09:43:45,778 [main] INFO  o.a.a.d.o.w.e.s.c.Controller Starting Cluster Controller ...... []
2021-06-10 09:43:45,947 [main] INFO  o.a.a.d.o.w.e.s.c.Controller Connection to helix cluster : datalake with name : datalake_controller []
2021-06-10 09:43:45,949 [main] INFO  o.a.a.d.o.w.e.s.c.Controller Zookeeper connection string localhost:2181 []
2021-06-10 09:46:12,810 [main] INFO  o.a.a.d.o.w.e.s.p.Participant Starting Participant v0.01-SNAPSHOT using Java 11.0.9 on Isurus-MacBook-Pro.local with PID 6945 (/Users/isururanawaka/Documents/Airavata_Repository/airavata-data-lake/data-orchestrator/workflow-engine/workflow-engine-core/target/workflow-engine-core-0.01-SNAPSHOT.jar started by isururanawaka in /Users/isururanawaka/Documents/Airavata_Repository/airavata-data-lake/data-orchestrator/workflow-engine/workflow-engine-core) []
2021-06-10 09:46:12,814 [main] INFO  o.a.a.d.o.w.e.s.p.Participant No active profile set, falling back to default profiles: default []
2021-06-10 09:46:13,774 [main] INFO  o.a.a.d.o.w.e.s.p.Participant Started Participant in 1.405 seconds (JVM running for 1.952) []
2021-06-10 09:46:13,775 [main] INFO  o.a.a.d.o.w.e.s.p.Participant Staring Participant ..... []
2021-06-10 09:46:13,824 [main] INFO  o.a.a.d.o.w.e.s.p.Participant Loading task list file task-list.yaml from class path []
2021-06-10 09:46:13,849 [main] INFO  o.a.a.d.o.w.e.s.p.Participant Loading blocking task org.apache.airavata.datalake.orchestrator.workflow.engine.task.impl.ExampleBlockingTask []
2021-06-10 09:46:13,850 [main] INFO  o.a.a.d.o.w.e.s.p.Participant Loading non blocking task org.apache.airavata.datalake.orchestrator.workflow.engine.task.impl.ExampleNonBlockingTask []
2021-06-10 09:46:13,850 [main] INFO  o.a.a.d.o.w.e.s.p.Participant Loading non blocking task org.apache.airavata.datalake.orchestrator.workflow.engine.task.impl.AsyncDataTransferTask []
2021-06-10 09:46:14,158 [main] INFO  o.a.a.d.o.w.e.s.p.Participant Participant: datalake_participant has been added to cluster: datalake []
2021-06-10 09:46:14,302 [main] INFO  o.a.a.d.o.w.e.s.p.Participant Loading blocking task org.apache.airavata.datalake.orchestrator.workflow.engine.task.impl.ExampleBlockingTask []
2021-06-10 09:46:14,305 [main] INFO  o.a.a.d.o.w.e.s.p.Participant Loading non blocking task org.apache.airavata.datalake.orchestrator.workflow.engine.task.impl.ExampleNonBlockingTask []
2021-06-10 09:46:14,306 [main] INFO  o.a.a.d.o.w.e.s.p.Participant Loading non blocking task org.apache.airavata.datalake.orchestrator.workflow.engine.task.impl.AsyncDataTransferTask []
2021-06-10 09:46:14,612 [main] INFO  o.a.a.d.o.w.e.s.p.Participant Participant: datalake_participant, has connected to cluster: datalake []
2021-06-10 09:47:46,386 [main] INFO  o.a.a.d.o.w.e.s.h.APIRunner Starting APIRunner v0.01-SNAPSHOT using Java 11.0.9 on Isurus-MacBook-Pro.local with PID 7011 (/Users/isururanawaka/Documents/Airavata_Repository/airavata-data-lake/data-orchestrator/workflow-engine/workflow-engine-core/target/workflow-engine-core-0.01-SNAPSHOT.jar started by isururanawaka in /Users/isururanawaka/Documents/Airavata_Repository/airavata-data-lake/data-orchestrator/workflow-engine/workflow-engine-core) []
2021-06-10 09:47:46,390 [main] INFO  o.a.a.d.o.w.e.s.h.APIRunner No active profile set, falling back to default profiles: default []
2021-06-10 09:47:47,548 [main] INFO  o.a.k.c.c.ConsumerConfig ConsumerConfig values: 
	allow.auto.create.topics = true
	auto.commit.interval.ms = 5000
	auto.offset.reset = latest
	bootstrap.servers = [localhost:9092]
	check.crcs = true
	client.dns.lookup = default
	client.id = 
	client.rack = 
	connections.max.idle.ms = 540000
	default.api.timeout.ms = 60000
	enable.auto.commit = false
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = mft-even-group
	group.instance.id = null
	heartbeat.interval.ms = 3000
	interceptor.classes = []
	internal.leave.group.on.close = true
	isolation.level = read_uncommitted
	key.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
	max.partition.fetch.bytes = 1048576
	max.poll.interval.ms = 300000
	max.poll.records = 20
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	session.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = https
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	value.deserializer = class org.apache.airavata.datalake.orchestrator.workflow.engine.monitor.filter.mft.DataTransferEventDeserializer
 []
2021-06-10 09:47:47,633 [main] INFO  o.a.k.c.utils.AppInfoParser Kafka version: 2.3.0 []
2021-06-10 09:47:47,633 [main] INFO  o.a.k.c.utils.AppInfoParser Kafka commitId: fc1aaa116b661c8a []
2021-06-10 09:47:47,634 [main] INFO  o.a.k.c.utils.AppInfoParser Kafka startTimeMs: 1623332867631 []
2021-06-10 09:47:47,636 [main] INFO  o.a.k.c.consumer.KafkaConsumer [Consumer clientId=consumer-1, groupId=mft-even-group] Subscribed to topic(s): mft-status-topic []
2021-06-10 09:47:47,636 [main] INFO  o.a.a.d.o.w.e.s.w.d.DataSyncWorkflowManager Successfully initialized DatasyncWorkflow Manager []
2021-06-10 09:47:47,928 [pool-3-thread-1] WARN  o.a.k.clients.NetworkClient [Consumer clientId=consumer-1, groupId=mft-even-group] Error while fetching metadata with correlation id 2 : {mft-status-topic=LEADER_NOT_AVAILABLE} []
2021-06-10 09:47:47,931 [pool-3-thread-1] INFO  o.a.kafka.clients.Metadata [Consumer clientId=consumer-1, groupId=mft-even-group] Cluster ID: Gol-udpVSImhuI9CwwtVIw []
2021-06-10 09:47:47,932 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 09:47:47,934 [pool-3-thread-1] INFO  o.a.k.c.c.i.ConsumerCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Revoking previously assigned partitions [] []
2021-06-10 09:47:47,934 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] (Re-)joining group []
2021-06-10 09:47:47,939 [main] INFO  o.a.a.d.o.w.e.s.h.APIRunner Started APIRunner in 2.155 seconds (JVM running for 2.705) []
2021-06-10 09:47:47,941 [main] INFO  o.l.s.grpc.GRpcServerRunner Starting gRPC Server ... []
2021-06-10 09:47:47,952 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] (Re-)joining group []
2021-06-10 09:47:47,973 [main] INFO  o.l.s.grpc.GRpcServerRunner 'org.apache.airavata.datalake.orchestrator.workflow.engine.services.handler.WorkflowEngineAPIHandler' service has been registered. []
2021-06-10 09:47:48,038 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Successfully joined group with generation 1 []
2021-06-10 09:47:48,043 [pool-3-thread-1] INFO  o.a.k.c.c.i.ConsumerCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Setting newly assigned partitions: mft-status-topic-0 []
2021-06-10 09:47:48,050 [pool-3-thread-1] INFO  o.a.k.c.c.i.ConsumerCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Found no committed offset for partition mft-status-topic-0 []
2021-06-10 09:47:48,060 [pool-3-thread-1] INFO  o.a.k.c.c.i.SubscriptionState [Consumer clientId=consumer-1, groupId=mft-even-group] Resetting offset for partition mft-status-topic-0 to offset 0. []
2021-06-10 09:47:48,122 [main] INFO  o.l.s.grpc.GRpcServerRunner gRPC Server started, listening on port 6565. []
2021-06-10 15:24:57,529 [kafka-coordinator-heartbeat-thread | mft-even-group] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 15:24:57,529 [pool-3-thread-1] INFO  o.a.k.c.FetchSessionHandler [Consumer clientId=consumer-1, groupId=mft-even-group] Error sending fetch request (sessionId=233224597, epoch=40111) to node 0: org.apache.kafka.common.errors.DisconnectException. []
2021-06-10 15:24:57,565 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 15:24:57,565 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 15:24:57,668 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 15:25:29,781 [kafka-coordinator-heartbeat-thread | mft-even-group] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 15:25:29,804 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 15:25:29,805 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 15:25:29,907 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 15:26:14,488 [kafka-coordinator-heartbeat-thread | mft-even-group] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 15:26:14,512 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 15:26:14,513 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 15:26:14,615 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 15:26:43,612 [kafka-coordinator-heartbeat-thread | mft-even-group] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 15:26:43,614 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 15:26:43,614 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 15:26:43,715 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 15:27:16,297 [kafka-coordinator-heartbeat-thread | mft-even-group] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 15:27:16,315 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 15:27:16,316 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 15:27:16,418 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 15:38:13,763 [pool-3-thread-1] INFO  o.a.k.c.FetchSessionHandler [Consumer clientId=consumer-1, groupId=mft-even-group] Error sending fetch request (sessionId=7198562, epoch=200) to node 0: org.apache.kafka.common.errors.DisconnectException. []
2021-06-10 15:38:13,765 [kafka-coordinator-heartbeat-thread | mft-even-group] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 15:38:13,849 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 16:01:28,836 [kafka-coordinator-heartbeat-thread | mft-even-group] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 16:01:28,836 [pool-3-thread-1] INFO  o.a.k.c.FetchSessionHandler [Consumer clientId=consumer-1, groupId=mft-even-group] Error sending fetch request (sessionId=298420556, epoch=2359) to node 0: org.apache.kafka.common.errors.DisconnectException. []
2021-06-10 16:01:28,894 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 16:33:36,162 [kafka-coordinator-heartbeat-thread | mft-even-group] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 16:33:36,184 [pool-3-thread-1] INFO  o.a.k.c.FetchSessionHandler [Consumer clientId=consumer-1, groupId=mft-even-group] Error sending fetch request (sessionId=1813769218, epoch=140) to node 0: org.apache.kafka.common.errors.DisconnectException. []
2021-06-10 16:33:36,237 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 16:49:50,483 [pool-3-thread-1] INFO  o.a.k.c.FetchSessionHandler [Consumer clientId=consumer-1, groupId=mft-even-group] Error sending fetch request (sessionId=1261474758, epoch=319) to node 0: org.apache.kafka.common.errors.DisconnectException. []
2021-06-10 16:49:50,485 [kafka-coordinator-heartbeat-thread | mft-even-group] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 16:49:50,546 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 16:49:50,546 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 16:49:50,647 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 17:35:34,818 [pool-3-thread-1] INFO  o.a.k.c.FetchSessionHandler [Consumer clientId=consumer-1, groupId=mft-even-group] Error sending fetch request (sessionId=1664874349, epoch=1762) to node 0: org.apache.kafka.common.errors.DisconnectException. []
2021-06-10 17:35:34,818 [kafka-coordinator-heartbeat-thread | mft-even-group] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 17:35:34,897 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 17:36:44,327 [kafka-coordinator-heartbeat-thread | mft-even-group] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 17:36:44,352 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 17:36:44,352 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 17:36:44,453 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 18:17:19,797 [pool-3-thread-1] INFO  o.a.k.c.FetchSessionHandler [Consumer clientId=consumer-1, groupId=mft-even-group] Error sending fetch request (sessionId=439249689, epoch=209) to node 0: org.apache.kafka.common.errors.DisconnectException. []
2021-06-10 18:17:19,798 [kafka-coordinator-heartbeat-thread | mft-even-group] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 18:17:19,872 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 18:18:20,964 [kafka-coordinator-heartbeat-thread | mft-even-group] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 18:18:20,970 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 18:18:20,970 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 18:18:21,073 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 18:31:51,847 [pool-3-thread-1] INFO  o.a.k.c.FetchSessionHandler [Consumer clientId=consumer-1, groupId=mft-even-group] Error sending fetch request (sessionId=1020101565, epoch=212) to node 0: org.apache.kafka.common.errors.DisconnectException. []
2021-06-10 18:31:51,848 [kafka-coordinator-heartbeat-thread | mft-even-group] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 18:31:51,911 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 18:34:24,551 [kafka-coordinator-heartbeat-thread | mft-even-group] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 18:34:45,626 [pool-3-thread-1] INFO  o.a.k.c.FetchSessionHandler [Consumer clientId=consumer-1, groupId=mft-even-group] Error sending fetch request (sessionId=557012809, epoch=275) to node 0: org.apache.kafka.common.errors.DisconnectException. []
2021-06-10 18:34:45,886 [pool-3-thread-1] WARN  o.a.k.clients.NetworkClient [Consumer clientId=consumer-1, groupId=mft-even-group] Error connecting to node 192.168.0.2:9092 (id: 0 rack: null) []
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:68)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1114)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1005)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:537)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:259)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:326)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1251)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager.lambda$runKafkaConsumer$1(DataSyncWorkflowManager.java:124)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager$$Lambda$384/000000000000000000.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
2021-06-10 18:34:45,944 [pool-3-thread-1] WARN  o.a.k.clients.NetworkClient [Consumer clientId=consumer-1, groupId=mft-even-group] Error connecting to node 192.168.0.2:9092 (id: 0 rack: null) []
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:68)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1114)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1005)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:537)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:259)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:326)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1251)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager.lambda$runKafkaConsumer$1(DataSyncWorkflowManager.java:124)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager$$Lambda$384/000000000000000000.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
2021-06-10 18:34:46,153 [pool-3-thread-1] WARN  o.a.k.clients.NetworkClient [Consumer clientId=consumer-1, groupId=mft-even-group] Error connecting to node 192.168.0.2:9092 (id: 0 rack: null) []
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:68)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1114)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1005)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:537)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:259)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:326)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1251)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager.lambda$runKafkaConsumer$1(DataSyncWorkflowManager.java:124)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager$$Lambda$384/000000000000000000.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
2021-06-10 18:34:46,573 [pool-3-thread-1] WARN  o.a.k.clients.NetworkClient [Consumer clientId=consumer-1, groupId=mft-even-group] Error connecting to node 192.168.0.2:9092 (id: 0 rack: null) []
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:68)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1114)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1005)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:537)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:259)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:326)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1251)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager.lambda$runKafkaConsumer$1(DataSyncWorkflowManager.java:124)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager$$Lambda$384/000000000000000000.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
2021-06-10 18:34:47,394 [pool-3-thread-1] WARN  o.a.k.clients.NetworkClient [Consumer clientId=consumer-1, groupId=mft-even-group] Error connecting to node 192.168.0.2:9092 (id: 0 rack: null) []
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:68)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1114)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1005)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:537)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:259)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:326)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1251)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager.lambda$runKafkaConsumer$1(DataSyncWorkflowManager.java:124)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager$$Lambda$384/000000000000000000.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
2021-06-10 18:34:48,454 [pool-3-thread-1] WARN  o.a.k.clients.NetworkClient [Consumer clientId=consumer-1, groupId=mft-even-group] Error connecting to node 192.168.0.2:9092 (id: 0 rack: null) []
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:68)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1114)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1005)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:537)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:259)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:326)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1251)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager.lambda$runKafkaConsumer$1(DataSyncWorkflowManager.java:124)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager$$Lambda$384/000000000000000000.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
2021-06-10 18:34:49,303 [pool-3-thread-1] WARN  o.a.k.clients.NetworkClient [Consumer clientId=consumer-1, groupId=mft-even-group] Error connecting to node 192.168.0.2:9092 (id: 0 rack: null) []
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:68)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1114)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1005)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:537)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:259)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:326)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1251)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager.lambda$runKafkaConsumer$1(DataSyncWorkflowManager.java:124)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager$$Lambda$384/000000000000000000.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
2021-06-10 18:34:50,145 [pool-3-thread-1] WARN  o.a.k.clients.NetworkClient [Consumer clientId=consumer-1, groupId=mft-even-group] Error connecting to node 192.168.0.2:9092 (id: 0 rack: null) []
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:68)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1114)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1005)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:537)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:259)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:326)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1251)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager.lambda$runKafkaConsumer$1(DataSyncWorkflowManager.java:124)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager$$Lambda$384/000000000000000000.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
2021-06-10 18:34:51,096 [pool-3-thread-1] WARN  o.a.k.clients.NetworkClient [Consumer clientId=consumer-1, groupId=mft-even-group] Error connecting to node 192.168.0.2:9092 (id: 0 rack: null) []
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:68)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1114)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1005)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:537)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:259)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:326)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1251)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager.lambda$runKafkaConsumer$1(DataSyncWorkflowManager.java:124)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager$$Lambda$384/000000000000000000.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
2021-06-10 18:34:51,946 [pool-3-thread-1] WARN  o.a.k.clients.NetworkClient [Consumer clientId=consumer-1, groupId=mft-even-group] Error connecting to node 192.168.0.2:9092 (id: 0 rack: null) []
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:68)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1114)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1005)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:537)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:259)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:326)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1251)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager.lambda$runKafkaConsumer$1(DataSyncWorkflowManager.java:124)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager$$Lambda$384/000000000000000000.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
2021-06-10 18:34:52,997 [pool-3-thread-1] WARN  o.a.k.clients.NetworkClient [Consumer clientId=consumer-1, groupId=mft-even-group] Error connecting to node 192.168.0.2:9092 (id: 0 rack: null) []
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:68)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1114)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1005)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:537)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:259)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:326)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1251)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager.lambda$runKafkaConsumer$1(DataSyncWorkflowManager.java:124)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager$$Lambda$384/000000000000000000.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
2021-06-10 18:34:54,156 [pool-3-thread-1] WARN  o.a.k.clients.NetworkClient [Consumer clientId=consumer-1, groupId=mft-even-group] Error connecting to node 192.168.0.2:9092 (id: 0 rack: null) []
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:68)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1114)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1005)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:537)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:259)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:326)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1251)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager.lambda$runKafkaConsumer$1(DataSyncWorkflowManager.java:124)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager$$Lambda$384/000000000000000000.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
2021-06-10 18:34:55,151 [pool-3-thread-1] WARN  o.a.k.clients.NetworkClient [Consumer clientId=consumer-1, groupId=mft-even-group] Error connecting to node 192.168.0.2:9092 (id: 0 rack: null) []
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:68)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1114)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1005)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:537)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:259)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:326)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1251)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager.lambda$runKafkaConsumer$1(DataSyncWorkflowManager.java:124)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager$$Lambda$384/000000000000000000.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
2021-06-10 18:34:56,104 [pool-3-thread-1] WARN  o.a.k.clients.NetworkClient [Consumer clientId=consumer-1, groupId=mft-even-group] Error connecting to node 192.168.0.2:9092 (id: 0 rack: null) []
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:68)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1114)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1005)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:537)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:259)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:326)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1251)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager.lambda$runKafkaConsumer$1(DataSyncWorkflowManager.java:124)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager$$Lambda$384/000000000000000000.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
2021-06-10 18:34:57,055 [pool-3-thread-1] WARN  o.a.k.clients.NetworkClient [Consumer clientId=consumer-1, groupId=mft-even-group] Error connecting to node 192.168.0.2:9092 (id: 0 rack: null) []
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:68)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1114)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1005)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:537)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:259)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:326)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1251)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager.lambda$runKafkaConsumer$1(DataSyncWorkflowManager.java:124)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager$$Lambda$384/000000000000000000.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
2021-06-10 18:34:58,022 [pool-3-thread-1] WARN  o.a.k.clients.NetworkClient [Consumer clientId=consumer-1, groupId=mft-even-group] Error connecting to node 192.168.0.2:9092 (id: 0 rack: null) []
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:68)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1114)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1005)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:537)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:259)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:326)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1251)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager.lambda$runKafkaConsumer$1(DataSyncWorkflowManager.java:124)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager$$Lambda$384/000000000000000000.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
2021-06-10 18:34:58,903 [pool-3-thread-1] WARN  o.a.k.clients.NetworkClient [Consumer clientId=consumer-1, groupId=mft-even-group] Error connecting to node 192.168.0.2:9092 (id: 0 rack: null) []
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:68)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1114)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1005)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:537)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:259)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:326)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1251)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager.lambda$runKafkaConsumer$1(DataSyncWorkflowManager.java:124)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager$$Lambda$384/000000000000000000.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
2021-06-10 18:35:00,062 [pool-3-thread-1] WARN  o.a.k.clients.NetworkClient [Consumer clientId=consumer-1, groupId=mft-even-group] Error connecting to node 192.168.0.2:9092 (id: 0 rack: null) []
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:68)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1114)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1005)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:537)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:259)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:326)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1251)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager.lambda$runKafkaConsumer$1(DataSyncWorkflowManager.java:124)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager$$Lambda$384/000000000000000000.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
2021-06-10 18:35:49,906 [pool-3-thread-1] WARN  o.a.k.clients.NetworkClient [Consumer clientId=consumer-1, groupId=mft-even-group] Error connecting to node 192.168.0.2:9092 (id: 0 rack: null) []
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:474)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:252)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:212)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:249)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:326)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1251)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager.lambda$runKafkaConsumer$1(DataSyncWorkflowManager.java:124)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager$$Lambda$384/000000000000000000.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
2021-06-10 18:35:50,739 [pool-3-thread-1] WARN  o.a.k.clients.NetworkClient [Consumer clientId=consumer-1, groupId=mft-even-group] Error connecting to node 192.168.0.2:9092 (id: 0 rack: null) []
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:476)
	at java.base/sun.nio.ch.Net.connect(Net.java:468)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:694)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:945)
	at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:68)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1114)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1005)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:537)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:259)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:326)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1251)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager.lambda$runKafkaConsumer$1(DataSyncWorkflowManager.java:124)
	at org.apache.airavata.datalake.orchestrator.workflow.engine.services.wm.datasync.DataSyncWorkflowManager$$Lambda$384/000000000000000000.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
2021-06-10 18:35:51,805 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 18:35:51,854 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Attempt to heartbeat failed for since member id consumer-1-d1eb9f08-09cf-40c7-9f17-c9af3a6ef942 is not valid. []
2021-06-10 18:35:51,855 [pool-3-thread-1] INFO  o.a.k.c.c.i.ConsumerCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Revoking previously assigned partitions [mft-status-topic-0] []
2021-06-10 18:35:51,857 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] (Re-)joining group []
2021-06-10 18:35:51,873 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] (Re-)joining group []
2021-06-10 18:35:51,910 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Successfully joined group with generation 3 []
2021-06-10 18:35:51,910 [pool-3-thread-1] INFO  o.a.k.c.c.i.ConsumerCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Setting newly assigned partitions: mft-status-topic-0 []
2021-06-10 18:35:51,922 [pool-3-thread-1] INFO  o.a.k.c.c.i.ConsumerCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Found no committed offset for partition mft-status-topic-0 []
2021-06-10 18:35:52,516 [pool-3-thread-1] INFO  o.a.k.c.c.i.SubscriptionState [Consumer clientId=consumer-1, groupId=mft-even-group] Resetting offset for partition mft-status-topic-0 to offset 0. []
2021-06-10 18:49:53,103 [pool-3-thread-1] INFO  o.a.k.c.FetchSessionHandler [Consumer clientId=consumer-1, groupId=mft-even-group] Error sending fetch request (sessionId=1813789823, epoch=103) to node 0: org.apache.kafka.common.errors.DisconnectException. []
2021-06-10 18:49:53,103 [kafka-coordinator-heartbeat-thread | mft-even-group] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 18:49:53,158 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 18:53:00,273 [kafka-coordinator-heartbeat-thread | mft-even-group] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 18:53:00,280 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 18:53:00,281 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 18:53:00,383 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 19:32:32,805 [pool-3-thread-1] INFO  o.a.k.c.FetchSessionHandler [Consumer clientId=consumer-1, groupId=mft-even-group] Error sending fetch request (sessionId=3749923, epoch=745) to node 0: org.apache.kafka.common.errors.DisconnectException. []
2021-06-10 19:32:32,806 [kafka-coordinator-heartbeat-thread | mft-even-group] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 19:32:32,888 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 19:32:32,889 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 19:32:32,989 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 19:36:12,805 [pool-3-thread-1] INFO  o.a.k.c.FetchSessionHandler [Consumer clientId=consumer-1, groupId=mft-even-group] Error sending fetch request (sessionId=1474812023, epoch=105) to node 0: org.apache.kafka.common.errors.DisconnectException. []
2021-06-10 19:36:12,806 [kafka-coordinator-heartbeat-thread | mft-even-group] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 19:36:12,887 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 19:36:12,889 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 19:36:12,991 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 19:44:43,833 [pool-3-thread-1] INFO  o.a.k.c.FetchSessionHandler [Consumer clientId=consumer-1, groupId=mft-even-group] Error sending fetch request (sessionId=1517925000, epoch=215) to node 0: org.apache.kafka.common.errors.DisconnectException. []
2021-06-10 19:44:43,833 [kafka-coordinator-heartbeat-thread | mft-even-group] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 19:44:43,911 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
2021-06-10 20:12:59,363 [pool-3-thread-1] INFO  o.a.k.c.FetchSessionHandler [Consumer clientId=consumer-1, groupId=mft-even-group] Error sending fetch request (sessionId=275196156, epoch=427) to node 0: org.apache.kafka.common.errors.DisconnectException. []
2021-06-10 20:12:59,364 [kafka-coordinator-heartbeat-thread | mft-even-group] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) is unavailable or invalid, will attempt rediscovery []
2021-06-10 20:12:59,465 [pool-3-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator [Consumer clientId=consumer-1, groupId=mft-even-group] Discovered group coordinator 192.168.0.2:9092 (id: 2147483647 rack: null) []
